Contato:
  type: entity
  table: contato
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
    ddi:
      type: integer
      unsigned: false
      nullable: true
    ddd:
      type: smallint
      nullable: false
    telefone:
      type: string
      length: 255
      fixed: false
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToOne:
    tiposContatos:
      targetEntity: TiposContatos
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        tipos_contatos_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
