PessoaFisicaEnderecos:
  type: entity
  table: pessoa_fisica_enderecos
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
  oneToOne:
    pessoaFisica:
      targetEntity: PessoaFisica
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        pessoa_fisica_id:
          referencedColumnName: id
      orphanRemoval: false
    endereco:
      targetEntity: Enderecos
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        endereco_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
