SfGuardRememberKey:
  type: entity
  table: sf_guard_remember_key
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
    ipAddress:
      id: true
      type: string
      length: 50
      fixed: false
      nullable: false
      column: ip_address
    rememberKey:
      type: string
      length: 32
      fixed: false
      nullable: true
      column: remember_key
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToOne:
    user:
      targetEntity: SfGuardUser
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
