TiposContatos:
  type: entity
  table: tipos_contatos
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
    nome:
      type: string
      length: 30
      fixed: false
      nullable: false
    descricao:
      type: string
      length: 1000
      fixed: false
      nullable: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  lifecycleCallbacks: {  }
