#SicoobSiccadBundle:
#    resource: "@SicoobSiccadBundle/Controller/"
#    type:     annotation
#    prefix:   /
    
SicoobSiccadBundle:
    resource: "@SicoobSiccadBundle/Resources/config/routing.yml"
    prefix:   /
    type: rest

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
